name: Python CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  flake8_and_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analyzing the code with flake8
        run: |
          flake8 -v --max-line-length=100 .
      - name: Install dependencies for example tests
        run: |
          pip install -r requirements.txt

      - name: Run example tests(easy)
        run: |
          cd examples/
          pytest -v -s -m "simple_process_test and easy" tests/
      - name: Run example tests(hard)
        run: |
          cd examples/
          pytest -v -s -m "simple_process_test and hard" tests/

      - name: Setup virtual port
        run: socat PTY,link=/tmp/ttyV0 PTY,link=/tmp/ttyV1 &
      - name: Run example.py in advance
        run: |
         cd examples
         ./example.py < /tmp/ttyV0 > /tmp/ttyV0 2>&1
      - name: Run device tests
        run: |
          cd examples
          pytest -v -s -m "device_test" tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        run: docker build -f examples/Dockerfile -t nn/example-app:latest ./
      - name: Run docker related tests(from outside)
        run: |
          cd examples/
          pytest -v -s -m "docker_test" tests/
      - name: Run docker and mount files and run tests(from inside)
        run: |
          START_PYTEST_CMD="pytest -v -s -m docker_inner_test tests/"
          docker run -i --rm -v $(pwd)/:/app/work -w /app/work/examples --name example_app nn/example-app:latest ${START_PYTEST_CMD}

      # TODO: Investigate how to do testing on GitHub Actions regarding SSH.
